services:
  web:
    build:
      context: ./WebService
    container_name: flask_web
    ports:
      - "5000:5000"
    volumes:
      - ./WebService/flaskr/instance:/app/flaskr/instance
    environment:
      - FLASK_APP=flaskr
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
